version: "3.0"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:v5.0
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - ServerIP=${SERVER_IP}
      - DNS1=10.0.0.2#5054
      - DNS2=no
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=${WEB_PASSWORD}
    volumes:
       - "./etc-pihole/:/etc/pihole/"
       - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
